services:
  db:
    image: postgres:16.3
    container_name: AsyncAPI
    restart: always
    env_file:
      - app.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5470:5432"

volumes:
  db-data: